%% Import data from text file
% Script for importing data from the following text file:
%
%    filename: C:\Users\Diego\switchdrive\Master of Science\P9 Master Thesis\05_Modellierung Zugsystem\Datenexport_NISV_BlattC_ZHUW_SP04_20210111_Bearbeitet2.csv
%
% Auto-generated by MATLAB on 23-Aug-2022 14:22:21

%% Set up the Import Options and import the data
opts = delimitedTextImportOptions("NumVariables", 6);

% Specify range and delimiter
opts.DataLines = [2, Inf];
opts.Delimiter = ";";

% Specify column names and types
opts.VariableNames = ["MIV", "DatumZeit", "km_bis", "U8minMittelkV", "I8minMittelA", "P8minMittelMW"];
opts.VariableTypes = ["double", "datetime", "double", "double", "double", "double"];

% Specify file level properties
opts.ExtraColumnsRule = "ignore";
opts.EmptyLineRule = "read";

% Specify variable properties
opts = setvaropts(opts, "DatumZeit", "InputFormat", "dd.MM.yyyy HH:mm");

% Import the data
Meas = readtable("C:\Users\Diego\switchdrive\Master of Science\P9 Master Thesis\05_Modellierung Zugsystem\Datenexport_NISV_BlattC_ZHUW_SP04_20210111_Bearbeitet2.csv", opts);


%% Clear temporary variables
clear opts

%% Correction of measurements for Impedance

